[[characters]]
name = "Precusor, Priest"

[characters.details.Agility]
label = "Agility"
dice = "2D+ 1"
skills = []

[characters.details.Coordination]
label = "Coordination"
dice = "2D+1"
skills = []

[characters.details.Physique]
label = "Physique"
dice = "2D+2"
skills = []

[characters.details.Intellect]
label = "Intellect"
dice = "2D+1"
skills = [
    { label = "scholar", dice = "3D" },
    { label = "speaking", dice = "2D+2" },
]

[characters.details.Charisma]
label = "Charisma"
dice = "2D+1"
skills = [
    { label = "charm", dice = "2D+2" },
    { label = "command", dice = "3D+1" },
    { label = "mettle", dice = "2D+2" },
    { label = "persuasion", dice = "2D+2" },
]

[characters.details.Acumen]
label = "Acumen"
dice = "2D"
skills = []

[characters.details.Miracles]
label = "Miracles"
dice = "4D"
skills = [
    { label = "divination", dice = "4D+2" },
    { label = "favor", dice = "6D+2" },
    { label = "strife", dice = "6D+2" },
]

[characters.details."Strength Damage"]
label = "Strength Damage"
value = "1D"
suffix = ":"

[characters.details.Move]
label = "Move"
value = "10"
suffix = ":"

[characters.details."Fate Points"]
label = "Fate Points"
value = "1"
suffix = ":"

[characters.details."Character Points"]
label = "Character Points"
value = "5"
suffix = ":"

[characters.details."Body Points"]
label = "Body Points"
value = "28"
suffix = ":"

[characters.details."Wound levels"]
label = "Wound levels"
value = "5"
suffix = ":"

[characters.details.Disadvantages]
label = "Disadvantages"
details = [
    { label = "Devotion", rank = "(R3)", details = ", to the Perpetual Falling Land" },
    { label = "Employed", rank = "(R3)", details = ", to the Perpetual Falling Land" },
]

[characters.details.Advantages]
label = "Advantages"

[[characters.details.Advantages.details]]
label = "Authority"
rank = "(R3)"
details = ", over the followers of the Perpetual Falling Land"

[characters.details.Special]
label = "Special"

[[characters.details.Special.details]]
label = "Skill Bonus : Leadership"
rank = "(R1)"
details = ", +1 bonus to command , intimidation , and persuasion totals"
