[[characters]]
name = "Shadohowl"

[characters.details.Agility]
label = "Agility"
dice = "3D"
skills = [
    { label = "acrobatics", dice = "7D" },
    { label = "dodge", dice = "7D+1" },
    { label = "fighting", dice = "9D+1" },
    { label = "melee combat", dice = "8D+1" },
    { label = "stealth", dice = "8D" },
]

[characters.details.Coordination]
label = "Coordination"
dice = "3D+1"
skills = [
    { label = "lockpicking", dice = "4D" },
    { label = "marksmanship", dice = "3D+2" },
    { label = "sleight of hand", dice = "3D+2" },
    { label = "throwing", dice = "4D+1" },
]

[characters.details.Physique]
label = "Physique"
dice = "2D+2"
skills = [
    { label = "lifting", dice = "7D" },
    { label = "running", dice = "4D+2" },
    { label = "stamina", dice = "4D" },
]

[characters.details.Intellect]
label = "Intellect"
dice = "3D"
skills = [
    { label = "cultures", dice = "4D" },
    { label = "speaking", dice = "4D+1" },
]

[characters.details.Acumen]
label = "Acumen"
dice = "3D"
skills = [
    { label = "artist origami", dice = "5D" },
    { label = "disguise", dice = "5D+2" },
    { label = "hide", dice = "3D+1" },
    { label = "tracking", dice = "4D" },
]

[characters.details.Charisma]
label = "Charisma"
dice = "3D"
skills = [
    { label = "intimidation", dice = "5D+1" },
    { label = "mettle", dice = "4D" },
]

[characters.details."Strength Damage"]
label = "Strength Damage"
value = "+6"
suffix = ": ( )"

[characters.details.Move]
label = "Move"
value = "10"
suffix = ":"

[characters.details."Fate Points"]
label = "Fate Points"
value = "1"
suffix = ":"

[characters.details."Character Points"]
label = "Character Points"
value = "4"
suffix = ":"

[characters.details."Body Points"]
label = "Body Points"
value = "28"
suffix = ":"

[characters.details."Wound levels"]
label = "Wound levels"
value = "5"
suffix = ":"

[characters.details.Disadvantages]
label = "Disadvantages"
details = [
    { label = "Debt", rank = "(R2)", details = ", to dark master ( s )" },
    { label = "Infamy", rank = "(R2)", details = ", cruel and fearsome opponent" },
    { label = "Devotion", rank = "(R1)", details = ", to causing pain and injury" },
    { label = "Quirk", rank = "(R1)", details = ", provok- able to blind rage" },
]

[characters.details.Advantages]
label = "Advantages"
details = [
    { label = "Fame", rank = "(R3)", details = ", dangerous and highly skilled opponent" },
    { label = "Size : Large", rank = "(R1)", details = ", scale value 3" },
]

[characters.details.Special]
label = "Special"

[[characters.details.Special.details]]
label = "Accelerated Healing"
rank = "(R1)"
details = ", +1 D to natural healing rate"

[[characters.details.Special.details]]
label = "Ambidextrous"
rank = "(R1)"
details = ", +1 to select skill totals when using two hands"

[[characters.details.Special.details]]
label = "Combat Sense"
rank = "(R1)"
details = ", combat modifier from surprise is at - 2"

[[characters.details.Special.details]]
label = "Increased Attribute : Agility , Physique"
rank = "(R6 each)"
details = ", +6 to related totals"

[[characters.details.Special.details]]
label = "Natural Armor"
rank = "(R1)"
details = ", +1 D to damage resistance totals"
