"""Template Characters"""

from opend6_tools.character import *

c_1 = Character(
    name="",
    occupation="",
    race="",
    gender="trans",
    age="",
    height="179cm",
    weight="100kg",
    physical_description="",
    agility=Agility(3 * D, {"riding": 1 * D + 1}),
    intellect=Intellect(3 * D, {"scholar": 0 * D + 1, "traps": 0 * D + 1}),
    coordination=Coordination(
        3 * D,
        {
            "charioteering": 0 * D,
            "lockpicking": 0 * D,
            "marksmanship": 0 * D,
            "pilotry": 0 * D,
            "sleight of hand": 0 * D,
            "throwing": 0 * D,
        },
    ),
    acumen=Acumen(
        5 * D, {"disguise": 0 * D + 2, "survival": 1 * D, "investigation": 1 * D}
    ),
    physique=Physique(
        3 * D, {"lifting": 0 * D, "running": 0 * D, "stamina": 0 * D, "swimming": 0 * D}
    ),
    charisma=Charisma(
        1 * D,
        {
            "bluff": 0 * D + 2,
            "animal handling": 0 * D + 2,
            "mettle": 0 * D + 1,
            "persuasion": 0 * D + 2,
        },
    ),
    extranormal=Magic(
        0 * D,
        {
            "alteration": 0 * D,
            "apportation": 0 * D,
            "conjuration": 0 * D,
            "divination": 0 * D,
        },
    ),
    advantages=[],
    disadvantages=OptionList(
        Devotion(rank=1, notes="TBD"),
        Age(rank=1, notes="TBD"),
        LanguageProblems(rank=1, notes="TBD"),
    ),
    special_abilities=OptionList(NaturalRangedWeapon(rank=1, notes="TBD")),
    description="",
    realm="Human realm",
    move=10,
    strength_damage=2 * D,
    body=39,
    wounds={
        "Mortal": "1-3",
        "Incapacitated": "4-7",
        "Severe": "8-15",
        "Wounded": "16-22",
        "Stunned": "23-30",
    },
    funds=2 * D,
    silver=120,
    fate_points=1,
    character_points=5,
    equipment=NoteList("Shovel", "Drum, handheld"),
    armor=NoteList("Padded leather"),
    weapons=NoteList("Hatchet"),
    spells=NoteList(),
    personality="",
    objectives="",
    native_language="",
    other_notes="",
)
c_2 = Character(
    name="",
    occupation="",
    race="",
    gender="trans",
    age="",
    height="180cm",
    weight="110kg",
    physical_description="",
    agility=Agility(3 * D, {"riding": 0 * D + 1}),
    intellect=Intellect(3 * D, {"cultures": 0 * D + 1}),
    coordination=Coordination(
        3 * D, {"lockpicking": 1 * D, "sleight of hand": 0 * D + 2}
    ),
    acumen=Acumen(1 * D + 1, {"hide": 0 * D + 1, "disguise": 1 * D, "tracking": 1 * D}),
    physique=Physique(4 * D, {"swimming": 1 * D}),
    charisma=Charisma(3 * D + 2, {"intimidation": 1 * D, "animal handling": 0 * D + 1}),
    extranormal=Magic(
        0 * D,
        {
            "alteration": 0 * D,
            "apportation": 0 * D,
            "conjuration": 0 * D,
            "divination": 0 * D,
        },
    ),
    advantages=OptionList(Fame(rank=1, notes="TBD")),
    disadvantages=OptionList(MinorStigma(rank=1, notes="TBD")),
    special_abilities=[],
    description="",
    realm="Human realm",
    move=10,
    strength_damage=2 * D,
    body=37,
    wounds={
        "Mortal": "1-3",
        "Incapacitated": "4-6",
        "Severe": "7-14",
        "Wounded": "15-21",
        "Stunned": "22-29",
    },
    funds=3 * D,
    silver=180,
    fate_points=1,
    character_points=5,
    equipment=[],
    armor=NoteList("Quilted silk"),
    weapons=NoteList("Nunchaku"),
    spells=NoteList(),
    personality="",
    objectives="",
    native_language="",
    other_notes="",
)
c_3 = Character(
    name="",
    occupation="",
    race="",
    gender="inter",
    age="",
    height="179cm",
    weight="94kg",
    physical_description="",
    agility=Agility(
        3 * D,
        {
            "acrobatics": 0 * D,
            "climbing": 0 * D,
            "contortion": 0 * D,
            "dodge": 0 * D,
            "fighting": 0 * D,
            "flying": 0 * D,
            "jumping": 0 * D,
            "melee combat": 0 * D,
            "combat": 0 * D,
            "riding": 0 * D,
            "stealth": 0 * D,
        },
    ),
    intellect=Intellect(1 * D + 1, {"devices": 0 * D + 2, "trading": 0 * D + 2}),
    coordination=Coordination(
        3 * D,
        {
            "charioteering": 0 * D,
            "lockpicking": 0 * D,
            "marksmanship": 0 * D,
            "pilotry": 0 * D,
            "sleight of hand": 0 * D,
            "throwing": 0 * D,
        },
    ),
    acumen=Acumen(4 * D + 2, {"crafting": 0 * D + 2, "survival": 0 * D + 2}),
    physique=Physique(3 * D, {"lifting": 0 * D + 1, "swimming": 1 * D}),
    charisma=Charisma(
        3 * D,
        {
            "charm": 0 * D + 2,
            "animal handling": 1 * D + 1,
            "mettle": 0 * D + 1,
            "command": 0 * D + 2,
        },
    ),
    extranormal=Magic(
        0 * D,
        {
            "alteration": 0 * D,
            "apportation": 0 * D,
            "conjuration": 0 * D,
            "divination": 0 * D,
        },
    ),
    advantages=[],
    disadvantages=[],
    special_abilities=OptionList(ExtraBodyPart(rank=1, notes="TBD")),
    description="",
    realm="Human realm",
    move=10,
    strength_damage=0 * D,
    body=24,
    wounds={
        "Mortal": "1",
        "Incapacitated": "2-4",
        "Severe": "5-9",
        "Wounded": "10-13",
        "Stunned": "14-18",
    },
    funds=2 * D,
    silver=120,
    fate_points=1,
    character_points=5,
    equipment=NoteList(
        "Parchment, rice paper, or vellum",
        "Mirror, silver",
        "Lamp, pottery",
        "Blanket, flannel single",
    ),
    armor=[],
    weapons=NoteList("Trident"),
    spells=NoteList(),
    personality="",
    objectives="",
    native_language="",
    other_notes="",
)
c_4 = Character(
    name="",
    occupation="",
    race="",
    gender="female",
    age="",
    height="175cm",
    weight="96kg",
    physical_description="",
    agility=Agility(
        3 * D, {"riding": 1 * D + 1, "climbing": 0 * D + 1, "melee combat": 0 * D + 2}
    ),
    intellect=Intellect(3 * D, {"trading": 1 * D}),
    coordination=Coordination(
        3 * D, {"lockpicking": 0 * D + 2, "marksmanship": 0 * D + 1}
    ),
    acumen=Acumen(1 * D + 1, {"crafting": 1 * D, "disguise": 0 * D + 2}),
    physique=Physique(4 * D + 2, {"lifting": 0 * D + 1}),
    charisma=Charisma(3 * D, {"command": 0 * D + 2}),
    extranormal=Magic(
        0 * D,
        {
            "alteration": 0 * D,
            "apportation": 0 * D,
            "conjuration": 0 * D,
            "divination": 0 * D,
        },
    ),
    advantages=[],
    disadvantages=[],
    special_abilities=[],
    description="",
    realm="Human realm",
    move=10,
    strength_damage=0 * D,
    body=37,
    wounds={
        "Mortal": "1-3",
        "Incapacitated": "4-6",
        "Severe": "7-14",
        "Wounded": "15-21",
        "Stunned": "22-29",
    },
    funds=3 * D,
    silver=180,
    fate_points=1,
    character_points=5,
    equipment=NoteList(
        "Scabbard",
        "Cloth, flannel, about 1 square meter",
        "Perfumed water in small glass vial",
        "Perfumed water in small glass vial",
    ),
    armor=NoteList("Hard leather"),
    weapons=NoteList("Katana"),
    spells=NoteList(),
    personality="",
    objectives="",
    native_language="",
    other_notes="",
)
c_5 = Character(
    name="",
    occupation="",
    race="",
    gender="trans",
    age="",
    height="179cm",
    weight="108kg",
    physical_description="",
    agility=Agility(
        5 * D,
        {"melee combat": 0 * D + 2, "climbing": 1 * D + 1, "contortion": 0 * D + 1},
    ),
    intellect=Intellect(
        3 * D, {"navigation": 1 * D, "trading": 0 * D + 1, "healing": 0 * D + 2}
    ),
    coordination=Coordination(
        3 * D,
        {
            "charioteering": 0 * D,
            "lockpicking": 0 * D,
            "marksmanship": 0 * D,
            "pilotry": 0 * D,
            "sleight of hand": 0 * D,
            "throwing": 0 * D,
        },
    ),
    acumen=Acumen(
        3 * D, {"survival": 0 * D + 2, "know-how": 0 * D + 1, "streetwise": 0 * D + 2}
    ),
    physique=Physique(
        3 * D, {"lifting": 0 * D, "running": 0 * D, "stamina": 0 * D, "swimming": 0 * D}
    ),
    charisma=Charisma(1 * D, {"charm": 1 * D}),
    extranormal=Magic(
        0 * D,
        {
            "alteration": 0 * D,
            "apportation": 0 * D,
            "conjuration": 0 * D,
            "divination": 0 * D,
        },
    ),
    advantages=[],
    disadvantages=OptionList(BadLuck(rank=1, notes="TBD"), Age(rank=1, notes="TBD")),
    special_abilities=OptionList(ArmorDefeatingAttack(rank=1, notes="TBD")),
    description="",
    realm="Human realm",
    move=10,
    strength_damage=2 * D,
    body=31,
    wounds={
        "Mortal": "1-2",
        "Incapacitated": "3-5",
        "Severe": "6-11",
        "Wounded": "12-18",
        "Stunned": "19-24",
    },
    funds=2 * D,
    silver=120,
    fate_points=1,
    character_points=5,
    equipment=NoteList(
        "Vial with stopper, glass", "Bell, small metal", "Lute", "Lockpicking tools"
    ),
    armor=NoteList("Quilted silk"),
    weapons=NoteList("Rapier"),
    spells=NoteList(),
    personality="",
    objectives="",
    native_language="",
    other_notes="",
)
c_6 = Character(
    name="",
    occupation="",
    race="",
    gender="trans",
    age="",
    height="186cm",
    weight="108kg",
    physical_description="",
    agility=Agility(
        1 * D + 2, {"flying": 0 * D + 2, "melee combat": 1 * D, "stealth": 0 * D + 2}
    ),
    intellect=Intellect(4 * D + 1, {"traps": 0 * D + 2}),
    coordination=Coordination(
        3 * D,
        {
            "charioteering": 0 * D,
            "lockpicking": 0 * D,
            "marksmanship": 0 * D,
            "pilotry": 0 * D,
            "sleight of hand": 0 * D,
            "throwing": 0 * D,
        },
    ),
    acumen=Acumen(
        3 * D, {"investigation": 1 * D, "search": 0 * D + 2, "tracking": 0 * D + 2}
    ),
    physique=Physique(3 * D, {"swimming": 0 * D + 2}),
    charisma=Charisma(3 * D, {"animal handling": 0 * D + 2, "command": 0 * D + 1}),
    extranormal=Magic(
        0 * D,
        {
            "alteration": 0 * D,
            "apportation": 0 * D,
            "conjuration": 0 * D,
            "divination": 0 * D,
        },
    ),
    advantages=OptionList(Fame(rank=1, notes="TBD")),
    disadvantages=OptionList(Employed(rank=1, notes="TBD")),
    special_abilities=[],
    description="",
    realm="Human realm",
    move=10,
    strength_damage=2 * D,
    body=30,
    wounds={
        "Mortal": "1-2",
        "Incapacitated": "3-5",
        "Severe": "6-11",
        "Wounded": "12-17",
        "Stunned": "18-23",
    },
    funds=4 * D,
    silver=240,
    fate_points=1,
    character_points=5,
    equipment=NoteList(
        "Marbles, hard clay",
        "Compass",
        "Holy symbol, silver unblessed",
        "Tent, two-person",
    ),
    armor=NoteList("Hides and fur, fur cloak"),
    weapons=NoteList("Hatchet"),
    spells=NoteList(),
    personality="",
    objectives="",
    native_language="",
    other_notes="",
)
c_7 = Character(
    name="",
    occupation="",
    race="",
    gender="trans",
    age="",
    height="178cm",
    weight="98kg",
    physical_description="",
    agility=Agility(
        4 * D + 1,
        {
            "combat": 0 * D + 1,
            "jumping": 0 * D + 1,
            "flying": 1 * D,
            "fighting": 1 * D + 1,
        },
    ),
    intellect=Intellect(2 * D + 2, {"traps": 0 * D + 2}),
    coordination=Coordination(2 * D, {"sleight of hand": 0 * D + 2}),
    acumen=Acumen(3 * D + 2, {"investigation": 0 * D + 2}),
    physique=Physique(3 * D, {"swimming": 1 * D}),
    charisma=Charisma(2 * D + 1, {"charm": 0 * D + 2, "mettle": 0 * D + 1}),
    extranormal=Magic(
        0 * D,
        {
            "alteration": 0 * D,
            "apportation": 0 * D,
            "conjuration": 0 * D,
            "divination": 0 * D,
        },
    ),
    advantages=[],
    disadvantages=OptionList(
        CulturalUnfamiliarity(rank=1, notes="TBD"),
        CulturalUnfamiliarity(rank=1, notes="TBD"),
        Quirk(rank=1, notes="TBD"),
        Hindrance(rank=1, notes="TBD"),
        Quirk(rank=1, notes="TBD"),
        Age(rank=1, notes="TBD"),
        Poverty(rank=1, notes="TBD"),
        Enemy(rank=1, notes="TBD"),
        BadLuck(rank=1, notes="TBD"),
        Enemy(rank=1, notes="TBD"),
    ),
    special_abilities=OptionList(PossessionFull(rank=1, notes="TBD")),
    description="",
    realm="Human realm",
    move=10,
    strength_damage=2 * D,
    body=32,
    wounds={
        "Mortal": "1-2",
        "Incapacitated": "3-5",
        "Severe": "6-12",
        "Wounded": "13-18",
        "Stunned": "19-25",
    },
    funds=3 * D,
    silver=180,
    fate_points=1,
    character_points=5,
    equipment=NoteList(
        "Waterskin", "Brazier, portable bronze", "Bowl, wooden soup", "Sealing wax"
    ),
    armor=NoteList("Bone and hide"),
    weapons=NoteList("Tonfa"),
    spells=NoteList(),
    personality="",
    objectives="",
    native_language="",
    other_notes="",
)
c_8 = Character(
    name="",
    occupation="",
    race="",
    gender="male",
    age="",
    height="186cm",
    weight="106kg",
    physical_description="",
    agility=Agility(
        3 * D,
        {
            "acrobatics": 0 * D,
            "climbing": 0 * D,
            "contortion": 0 * D,
            "dodge": 0 * D,
            "fighting": 0 * D,
            "flying": 0 * D,
            "jumping": 0 * D,
            "melee combat": 0 * D,
            "combat": 0 * D,
            "riding": 0 * D,
            "stealth": 0 * D,
        },
    ),
    intellect=Intellect(
        3 * D, {"traps": 1 * D, "healing": 1 * D, "cultures": 0 * D + 2}
    ),
    coordination=Coordination(
        3 * D, {"sleight of hand": 0 * D + 1, "pilotry": 0 * D + 2}
    ),
    acumen=Acumen(
        3 * D, {"investigation": 1 * D + 1, "know-how": 0 * D + 1, "search": 0 * D + 2}
    ),
    physique=Physique(5 * D, {"stamina": 0 * D + 1}),
    charisma=Charisma(1 * D, {"intimidation": 0 * D + 2}),
    extranormal=Magic(
        0 * D,
        {
            "alteration": 0 * D,
            "apportation": 0 * D,
            "conjuration": 0 * D,
            "divination": 0 * D,
        },
    ),
    advantages=OptionList(Size(rank=1, notes="TBD")),
    disadvantages=OptionList(Enemy(rank=1, notes="TBD")),
    special_abilities=[],
    description="",
    realm="Human realm",
    move=10,
    strength_damage=3 * D,
    body=41,
    wounds={
        "Mortal": "1-3",
        "Incapacitated": "4-7",
        "Severe": "8-15",
        "Wounded": "16-24",
        "Stunned": "25-32",
    },
    funds=2 * D,
    silver=120,
    fate_points=1,
    character_points=5,
    equipment=NoteList(
        "Candle, tallow taper; torch",
        "Bucket, wooden",
        "Bucket, wooden",
        "Mirror, silver",
    ),
    armor=NoteList("Bone and hide"),
    weapons=NoteList("Sap, hammer (tool)"),
    spells=NoteList(),
    personality="",
    objectives="",
    native_language="",
    other_notes="",
)
c_9 = Character(
    name="",
    occupation="",
    race="",
    gender="male",
    age="",
    height="178cm",
    weight="104kg",
    physical_description="",
    agility=Agility(
        2 * D, {"contortion": 0 * D + 2, "stealth": 1 * D, "combat": 1 * D}
    ),
    intellect=Intellect(
        2 * D + 2,
        {"reading/writing": 1 * D, "cultures": 0 * D + 2, "scholar": 0 * D + 2},
    ),
    coordination=Coordination(
        3 * D,
        {
            "charioteering": 0 * D,
            "lockpicking": 0 * D,
            "marksmanship": 0 * D,
            "pilotry": 0 * D,
            "sleight of hand": 0 * D,
            "throwing": 0 * D,
        },
    ),
    acumen=Acumen(2 * D + 1, {"artist": 1 * D, "tracking": 0 * D + 1}),
    physique=Physique(
        2 * D + 2,
        {"lifting": 0 * D, "running": 0 * D, "stamina": 0 * D, "swimming": 0 * D},
    ),
    charisma=Charisma(3 * D + 1, {"bluff": 0 * D + 1}),
    extranormal=Magic(2 * D, {"apportation": 0 * D + 1}),
    advantages=[],
    disadvantages=OptionList(Employed(rank=1, notes="TBD")),
    special_abilities=OptionList(MultipleAbilities(rank=1, notes="TBD")),
    description="",
    realm="Human realm",
    move=10,
    strength_damage=1 * D,
    body=32,
    wounds={
        "Mortal": "1-2",
        "Incapacitated": "3-5",
        "Severe": "6-12",
        "Wounded": "13-18",
        "Stunned": "19-25",
    },
    funds=3 * D,
    silver=180,
    fate_points=1,
    character_points=5,
    equipment=[],
    armor=NoteList("Soft leather, heavy fabric"),
    weapons=NoteList("Spear (metal tip)"),
    spells=NoteList(),
    personality="",
    objectives="",
    native_language="",
    other_notes="",
)
c_10 = Character(
    name="",
    occupation="",
    race="",
    gender="inter",
    age="",
    height="176cm",
    weight="84kg",
    physical_description="",
    agility=Agility(2 * D + 2, {"flying": 1 * D, "acrobatics": 0 * D + 2}),
    intellect=Intellect(3 * D + 1, {"healing": 1 * D, "traps": 0 * D + 2}),
    coordination=Coordination(1 * D + 1, {"sleight of hand": 0 * D + 1}),
    acumen=Acumen(2 * D + 1, {"streetwise": 1 * D}),
    physique=Physique(
        2 * D, {"lifting": 0 * D, "running": 0 * D, "stamina": 0 * D, "swimming": 0 * D}
    ),
    charisma=Charisma(4 * D, {"mettle": 0 * D + 2, "persuasion": 0 * D + 1}),
    extranormal=Miracles(2 * D + 1, {"strife": 0 * D + 1, "divination": 1 * D}),
    advantages=[],
    disadvantages=[],
    special_abilities=[],
    description="",
    realm="Human realm",
    move=10,
    strength_damage=1 * D,
    body=26,
    wounds={
        "Mortal": "1-2",
        "Incapacitated": "3-4",
        "Severe": "5-9",
        "Wounded": "10-15",
        "Stunned": "16-20",
    },
    funds=4 * D,
    silver=240,
    fate_points=1,
    character_points=5,
    equipment=NoteList("Mirror, silver", "Blanket, flannel single"),
    armor=NoteList("Hides and fur, fur cloak"),
    weapons=NoteList("Arrow, crossbow bolt, dart"),
    spells=NoteList(),
    personality="",
    objectives="",
    native_language="",
    other_notes="",
)
all_characters = {
    "c_1": c_1,
    "c_2": c_2,
    "c_3": c_3,
    "c_4": c_4,
    "c_5": c_5,
    "c_6": c_6,
    "c_7": c_7,
    "c_8": c_8,
    "c_9": c_9,
    "c_10": c_10,
}
if __name__ == "__main__":
    app = build_app(all_characters)
    app()
