[[characters]]
name = "Cernay Avers, Cleric"

[characters.details.Agility]
label = "Agility"
dice = "2D+1"
skills = [
    { label = "melee combat", dice = "4D+1" },
]

[characters.details.Coordination]
label = "Coordination"
dice = "2D"
skills = [
    { label = "throwing", dice = "2D+2" },
]

[characters.details.Physique]
label = "Physique"
dice = "2D"
skills = []

[characters.details.Intellect]
label = "Intellect"
dice = "3D"
skills = [
    { label = "cultures", dice = "4D" },
    { label = "reading/writing", dice = "3D+1" },
    { label = "scholar", dice = "3D+1" },
    { label = "speaking", dice = "3D+1" },
]

[characters.details.Acumen]
label = "Acumen"
dice = "3D"
skills = [
    { label = "search", dice = "3D+1" },
]

[characters.details.Charisma]
label = "Charisma"
dice = "3D"
skills = [
    { label = "mettle", dice = "4D" },
]

[characters.details.Miracles]
label = "Miracles"
dice = "2D"
skills = [
    { label = "divination", dice = "3D" },
    { label = "favor", dice = "2D+1" },
    { label = "strife", dice = "2D+2" },
]

[characters.details.Move]
label = "Move"
value = "10"
suffix = ": ."

[characters.details."Strength Damage"]
label = "Strength Damage"
value = "1D"
suffix = ": ."

[characters.details."Fate Points"]
label = "Fate Points"
value = "0"
suffix = ": ."

[characters.details."Character Points"]
label = "Character Points"
value = "2"
suffix = ": ."

[characters.details."Body Points"]
label = "Body Points"
value = "16"
suffix = ": /"

[characters.details."Wound levels"]
label = "Wound levels"
value = "3"
suffix = ": ."

[characters.details.Disadvantages]
label = "Disadvantages"
details = [
    { label = "Devotion", rank = "(R3)", details = ", to religion" },
    { label = "Employed", rank = "(R2)", details = ", must follow sect's regulations ." },
]

[characters.details.Equipment]
items = [
    { description = "robes", features = "" },
    { description = "coins", features = "" },
    { description = "pouches containing holy symbols", features = "" },
    { description = "mace", features = "( damage +1D+1 )" },
    { description = ".", features = "" },
]
label = "Equipment"
