[[characters]]
name = "Typical Library Guard"

[characters.details.Agility]
label = "Agility"
dice = "3D"
skills = [
    { label = "dodge", dice = "4D" },
    { label = "fighting", dice = "3D+2" },
    { label = "melee combat", dice = "4D" },
]

[characters.details.Coordination]
label = "Coordination"
dice = "2D"
skills = [
    { label = "marksmanship", dice = "3D" },
]

[characters.details.Physique]
label = "Physique"
dice = "4D"
skills = [
    { label = "running", dice = "4D+1" },
    { label = "Intel- lect", dice = "2D" },
    { label = "scholar", dice = "3D+2" },
]

[characters.details.Acumen]
label = "Acumen"
dice = "4D"
skills = [
    { label = "investigation", dice = "4D+1" },
    { label = "search", dice = "4D+1" },
    { label = "tracking", dice = "4D+2" },
]

[characters.details.Charisma]
label = "Charisma"
dice = "3D"
skills = [
    { label = "intimidation", dice = "3D+2" },
]

[characters.details.Move]
label = "Move"
value = "10"
suffix = ": ."

[characters.details."Strength Damage"]
label = "Strength Damage"
value = "2D"
suffix = ": ."

[characters.details."Fate Points"]
label = "Fate Points"
value = "0"
suffix = ": ."

[characters.details."Character Points"]
label = "Character Points"
value = "0"
suffix = ": ."

[characters.details."Body Points"]
label = "Body Points"
value = "17"
suffix = ": /"

[characters.details."Wound levels"]
label = "Wound levels"
value = "2"
suffix = ": ."

[characters.details.Equipment]
items = [
    { description = "hard leather armor", features = "( Armor Value +1D+1 )" },
    { description = "", features = "" },
    { description = "short sword", features = "( damage +1D+2 )" },
    { description = "", features = "" },
    { description = "short bow and 10 arrows", features = "( damage +1D+2 )" },
    { description = ".", features = "" },
]
label = "Equipment"
