[[characters]]
name = "Sofronius, Ruler"

[characters.details.Agility]
label = "Agility"
dice = "3D"
skills = [
    { label = "melee combat", dice = "4D+2" },
    { label = "riding", dice = "4D+1" },
]

[characters.details.Coordination]
label = "Coordination"
dice = "2D"
skills = [
    { label = "marksmanship", dice = "3D+2" },
]

[characters.details.Physique]
label = "Physique"
dice = "3D"
skills = [
    { label = "running", dice = "4D" },
    { label = "stamina", dice = "4D" },
]

[characters.details.Intellect]
label = "Intellect"
dice = "3D+2"
skills = [
    { label = "cultures", dice = "3D" },
    { label = "reading/writing", dice = "3D+1" },
    { label = "speaking", dice = "4D" },
]

[characters.details.Acumen]
label = "Acumen"
dice = "3D"
skills = [
    { label = "investigation", dice = "3D+2" },
    { label = "streetwise", dice = "3D+1" },
    { label = "search", dice = "3D+1" },
]

[characters.details.Charisma]
label = "Charisma"
dice = "3D+1"
skills = [
    { label = "bluff", dice = "3D+2" },
    { label = "persuasion", dice = "4D" },
]

[characters.details.Move]
label = "Move"
value = "10"
suffix = ": ."

[characters.details."Strength Damage"]
label = "Strength Damage"
value = "2D"
suffix = ": ."

[characters.details."Fate Points"]
label = "Fate Points"
value = "1"
suffix = ": ."

[characters.details."Character Points"]
label = "Character Points"
value = "4"
suffix = ": ."

[characters.details."Body Points"]
label = "Body Points"
value = "27"
suffix = ": /"

[characters.details."Wound levels"]
label = "Wound levels"
value = "4"
suffix = ": ."

[characters.details.Disadvantages]
label = "Disadvantages"
details = [
    { label = "Enemy", rank = "(R1)", details = ", there are those who envy his power ." },
]

[characters.details.Advantages]
label = "Advantages"
details = [
    { label = "Authority", rank = "(R3)", details = ", ruler" },
    { label = "Contacts", rank = "(R1)", details = ", members of the Assembly ." },
]

[characters.details.Equipment]
items = [
    { description = "robes", features = "" },
    { description = "small dagger", features = "( damage +2 )" },
    { description = ".", features = "" },
]
label = "Equipment"
